import { colors } from "@/styles/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray[50],
  },
  header: {
    paddingTop: 62,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingBottom: 16,
    gap: 16,
    backgroundColor: colors.basic.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
  },
  title: {
    flex: 1,
    color: colors.gray[700],
    fontSize: 20,
    fontWeight: "700",
  },
  form: {
    paddingHorizontal: 24,
    paddingTop: 12,
    gap: 16,
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  pathSelector: {
    width: "100%",
    backgroundColor: colors.basic.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.gray[300],
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  pathSelectorText: {
    fontSize: 16,
    color: colors.gray[600],
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: colors.basic.white,
    borderRadius: 16,
    padding: 24,
    width: "90%",
    maxHeight: "80%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
  },
  modalPath: {
    fontSize: 16,
    color: colors.gray[500],
    marginBottom: 16,
    textAlign: "center",
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
  },
  folderListContainer: {
    height: 300, // Adjust as needed
    marginBottom: 16,
  },
  cancelButton: {
    alignSelf: "center",
    marginTop: 16,
  },
  cancelButtonText: {
    color: colors.gray[400],
    fontSize: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.gray[200],
    backgroundColor: colors.gray[100],
    borderRadius: 8,
    padding: 16,
    fontSize: 16,
    color: colors.gray[600],
  },
  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    // marginTop: 16,
    marginBottom: 16,
  },
  label: {
    color: colors.gray[600],
    fontSize: 16,
    fontWeight: "500",
  },
});
